volumes:
  mysql:
  project:
  results:
  secrets:

services:
  mysql:
    container_name: boinc_mysql
    build:
      context: images/mysql
      target: mysql$DEFAULTARGS
    volumes:
      - "mysql:/var/lib/mysql"

  makeproject:
    container_name: boinc_mkproject
    build:
      context: images/makeproject
      target: makeproject$DEFAULTARGS
      args:
        - TAG
        - BOINC_USER
        - PROJECT_ROOT
    volumes:
      - "project:$PROJECT_ROOT.dst"
      - "secrets:/run/secrets"
    hostname: makeproject
    environment:
      - URL_BASE
      - PROJECT

  apache:
    container_name: boinc_apache
    build:
      context: images/apache
      target: apache$DEFAULTARGS
      args:
        - TAG
        - BOINC_USER
        - PROJECT_ROOT
    hostname: $PROJECT
    depends_on:
      - mysql
    volumes:
      - "project:$PROJECT_ROOT"
      - "results:/results"
      - "secrets:/run/secrets"
      - "/dev/null:/run/secrets/keys/code_sign_private"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80"
    tty: true
    environment:
      - URL_BASE
      - PROJECT