#==================================
FROM mariadb:lts-noble AS mysql
#==================================

ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

#==============================
FROM mysql AS mysql-defaultargs
#==============================
