name: BOINC Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # checkout root
    - name: Checkout submodules # checkout rest
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set make jobs
      run: |
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
    
    - name: Build the makeproject Docker image
      run: docker build images/makeproject --target makeproject --tag boysanic/boinc-server-docker-makeproject:latest
    
    - name: Build the apache Docker image
      run: docker build images/apache/ --target apache --tag boysanic/boinc-server-docker-apache:latest
    
    - name: Build the mysql Docker image  
      run: docker build images/mysql --target mysql --tag boysanic/boinc-server-docker-mysql:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push all to Docker Hub
      run : |
        docker image push boysanic/boinc-server-docker-makeproject:latest
        docker image push boysanic/boinc-server-docker-apache:latest
        docker image push boysanic/boinc-server-docker-mysql:latest
    
