name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the makeproject Docker image
      run: docker build images/makeproject --tag boysanic/boincserver_makeproject:latest
    - name: Build the apache Docker image
      run: docker build images/apache/ --tag boysanic/boinc_apache:latest
    - name: Build the mysql Docker image  
      run: docker build images/mysql --tag boysanic/boinc_mysql:latest
